CREATE database customer_behavior;
USE customer_behavior;
SELECT * FROM shopping_data limit 10;

-- Q1 what is the average age of customers?
SELECT AVG(Age) AS avg_age
FROM shopping_data;

-- Q2 Find the total number of unique customers
SELECT COUNT(DISTINCT Customer_ID) AS total_customers
FROM shopping_data;

-- Question 3: List all unique product categories
SELECT DISTINCT Category
FROM shopping_data;

-- Question 4: Analyze the gender distribution of customers
SELECT Gender, COUNT(*) AS total_customers
FROM shopping_data
GROUP BY Gender;

-- Question 5: Calculate the total revenue generated
SELECT SUM(Purchase_Amount) AS total_revenue
FROM shopping_data;

-- Question 6: Find total revenue generated by male versus female customers
SELECT Gender, SUM(Purchase_Amount) 
FROM shopping_data
GROUP BY Gender;

-- Question 7: Find total revenue by product category
SELECT Category, SUM(Purchase_Amount) AS revenue
FROM shopping_data
GROUP BY Category
ORDER BY revenue DESC;

-- Question 8: Find the average purchase amount by gender
SELECT Gender, AVG(Purchase_Amount) AS avg_purchase
FROM shopping_data
GROUP BY Gender;

-- Question 9: Identify the most frequently used payment method
SELECT Payment_Method, COUNT(*) AS usage_count
FROM shopping_data
GROUP BY Payment_Method
ORDER BY usage_count DESC
LIMIT 1;


-- Question 11: Analyze total revenue generated in each season
SELECT Season, SUM(Purchase_Amount) AS total_revenue
FROM shopping_data
GROUP BY Season
ORDER BY total_revenue DESC;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
age_group, SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue desc;


-- Q.11 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM shopping_data
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q12. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from shopping_data 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from shopping_data);

-- Q 13. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
 CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM shopping_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;